# ---- G-code Generation Functions ----
def generate_raster_gcode(
        stl_path: Path,
        out_path: Path,
        tool_diam: float = 3.0,
        stepover: float = 0.4,
        feed: float = 300.0,
        plunge: float = 120.0,
        clearance: float = 5.0,
        spindle: Optional[int] = 8000,
        dir_axis: str = "X",
        origin: str = "bbox_min",
        stepdown: float = 0.0,
        feed_rough: Optional[float] = None,
        feed_finish: Optional[float] = None,
        finish_stepover: Optional[float] = None,
        waterline: bool = False,
        waterline_dz: float = 0.0,
        allowance_x: float = 0.0,
        allowance_y: float = 0.0,
        allowance_z: float = 0.0,
        controller: str = "fanuc",
        operation_type: str = "milling"
) -> Dict:
    tool_diam = validate_float(tool_diam, 3.0, 0.1, 50.0)
    stepover = validate_float(stepover, 0.4, 0.05, 0.95)
    feed = validate_float(feed, 300.0, 10.0, 5000.0)
    plunge = validate_float(plunge, 120.0, 10.0, 2000.0)
    clearance = validate_float(clearance, 5.0, 1.0, 50.0)
    spindle = validate_int(spindle, 8000, 1000, 24000) if spindle else None
    stepdown = validate_float(stepdown, 0.0, 0.0, 50.0)
    feed_rough = validate_float(feed_rough, feed, 10.0, 5000.0) if feed_rough else feed
    feed_finish = validate_float(feed_finish, feed, 10.0, 5000.0) if feed_finish else feed
    finish_stepover = validate_float(finish_stepover, stepover, 0.05, 0.95) if finish_stepover else stepover
    waterline_dz = validate_float(waterline_dz, 0.0, 0.0, 50.0)

    step_xy = max(0.1, tool_diam * stepover)
    (xmin, xmax, ymin, ymax, zmin, zmax), z_func = build_top_sampler(stl_path, step_xy)

    # Apply allowances to geometry bounds
    xmin -= allowance_x
    xmax += allowance_x
    ymin -= allowance_y
    ymax += allowance_y
    zmax += allowance_z

    def estimate_cost(step: float) -> int:
        nx = max(2, int(math.ceil((xmax - xmin) / step)) + 1)
        ny = max(2, int(math.ceil((ymax - ymin) / step)) + 1)
        return nx * ny

    MAX_POINTS = 40000
    points = estimate_cost(step_xy)
    while points > MAX_POINTS:
        step_xy *= 1.3
        points = estimate_cost(step_xy)

    nx = max(2, int(math.ceil((xmax - xmin) / step_xy)) + 1)
    ny = max(2, int(math.ceil((ymax - ymin) / step_xy)) + 1)

    origin = origin if origin in ("bbox_min", "bbox_center", "bbox_top_center") else "bbox_min"
    ox, oy, oz = {
        "bbox_min": (xmin, ymin, zmin),
        "bbox_center": ((xmin + xmax) / 2.0, (ymin + ymax) / 2.0, zmin),
        "bbox_top_center": ((xmin + xmax) / 2.0, (ymin + ymax) / 2.0, zmax)
    }[origin]

    controller_settings = get_controller_settings(controller)

    def zigzag_lines():
        lines = []
        dir_axis_upper = dir_axis.upper()
        if dir_axis_upper == "X":
            ys = [ymin + i * step_xy for i in range(ny)]
            for j, y in enumerate(ys):
                xs = [xmin + i * step_xy for i in range(nx)]
                if j % 2 == 1:
                    xs.reverse()
                lines.append([(x, y) for x in xs])
        else:
            xs = [xmin + i * step_xy for i in range(nx)]
            for i, x in enumerate(xs):
                ys = [ymin + j * step_xy for j in range(ny)]
                if i % 2 == 1:
                    ys.reverse()
                lines.append([(x, y) for y in ys])
        return lines

    def sample_height_grid(step: float):
        xs = [xmin + i * step for i in range(nx)]
        ys = [ymin + j * step for j in range(ny)]
        Z = [[z_func(x, y) or -1e12 for x in xs] for y in ys]
        return xs, ys, Z

    with open(out_path, "w", encoding="ascii", errors="ignore") as f:
        w = f.write
        w(f"(Generated by CNCera - {operation_type.title()} - {controller.upper()})\n")
        w(f"(Origin: {origin})\n")

        for cmd in controller_settings["header"]:
            w(f"{cmd}\n")

        if spindle:
            w(f"{controller_settings['spindle_on'].format(spindle=spindle)}\n")
        w(f"{controller_settings['coolant_on']}\n")
        w(f"{controller_settings['rapid']} Z{clearance:.3f}\n")

        if stepdown > 0:
            zL = zmax
            while zL > zmin + 0.5 * stepdown:
                zL -= stepdown
                w(f"(Rough level Z={zL - oz:.3f})\n")
                for line in zigzag_lines():
                    x0, y0 = line[0]
                    w(f"{controller_settings['rapid']} X{(x0 - ox):.3f} Y{(y0 - oy):.3f}\n")
                    z0 = z_func(x0, y0)
                    if z0 is not None:
                        zt = min(z0, zL)
                        w(f"{controller_settings['linear']} Z{(zt - oz):.3f} F{plunge:.1f}\n")
                        w(f"F{feed_rough:.1f}\n")
                    else:
                        w(f"{controller_settings['rapid']} Z{clearance:.3f}\n")
                    for x, y in line[1:]:
                        z = z_func(x, y)
                        if z is None:
                            w(f"{controller_settings['rapid']} Z{clearance:.3f}\n{controller_settings['rapid']} X{(x - ox):.3f} Y{(y - oy):.3f}\n")
                        else:
                            zt = min(z, zL)
                            w(f"{controller_settings['linear']} X{(x - ox):.3f} Y{(y - oy):.3f} Z{(zt - oz):.3f}\n")
                w(f"{controller_settings['rapid']} Z{clearance:.3f}\n")

        if finish_stepover != stepover:
            step_fin_xy = max(0.05, tool_diam * finish_stepover)
            if step_fin_xy != step_xy:
                (xmin, xmax, ymin, ymax, _, _), z_func = build_top_sampler(stl_path, step_fin_xy)
                xmin -= allowance_x
                xmax += allowance_x
                ymin -= allowance_y
                ymax += allowance_y
                nx = max(2, int(math.ceil((xmax - xmin) / step_fin_xy)) + 1)
                ny = max(2, int(math.ceil((ymax - ymin) / step_fin_xy)) + 1)

        w("(Finish pass)\n")
        for line in zigzag_lines():
            x0, y0 = line[0]
            w(f"{controller_settings['rapid']} X{(x0 - ox):.3f} Y{(y0 - oy):.3f}\n")
            z0 = z_func(x0, y0)
            if z0 is not None:
                w(f"{controller_settings['linear']} Z{(z0 - oz):.3f} F{plunge:.1f}\n")
                w(f"F{feed_finish:.1f}\n")
            else:
                w(f"{controller_settings['rapid']} Z{clearance:.3f}\n")
            for x, y in line[1:]:
                z = z_func(x, y)
                if z is None:
                    w(f"{controller_settings['rapid']} Z{clearance:.3f}\n{controller_settings['rapid']} X{(x - ox):.3f} Y{(y - oy):.3f}\n")
                else:
                    w(f"{controller_settings['linear']} X{(x - ox):.3f} Y{(y - oy):.3f} Z{(z - oz):.3f}\n")
        w(f"{controller_settings['rapid']} Z{clearance:.3f}\n")

        if waterline and waterline_dz > 0:
            w("(Waterline)\n")
            xs, ys, Z = sample_height_grid(max(step_xy, tool_diam * 0.6))
            cur = zmax
            while cur > zmin + 0.5 * waterline_dz:
                cur -= waterline_dz
                loops = marching_squares(Z, xs, ys, cur)
                for loop in loops:
                    sx, sy = loop[0]
                    w(f"{controller_settings['rapid']} X{(sx - ox):.3f} Y{(sy - oy):.3f} Z{clearance:.3f}\n")
                    w(f"{controller_settings['linear']} Z{(cur - oz):.3f} F{plunge:.1f}\n")
                    w(f"F{feed_finish:.1f}\n")
                    for x, y in loop[1:]:
                        w(f"{controller_settings['linear']} X{(x - ox):.3f} Y{(y - oy):.3f} Z{(cur - oz):.3f}\n")
                    w(f"{controller_settings['rapid']} Z{clearance:.3f}\n")

        w(f"{controller_settings['coolant_off']}\n")
        if spindle:
            w(f"{controller_settings['spindle_off']}\n")
        w(f"{controller_settings['program_end']}\n")

    return {
        "bbox": {"xmin": xmin, "xmax": xmax, "ymin": ymin, "ymax": ymax, "zmin": zmin, "zmax": zmax},
        "grid": {"nx": nx, "ny": ny, "step_xy": step_xy},
        "origin": {"ox": ox, "oy": oy, "oz": oz}
    }

@app.route("/generate_gcode", methods=["POST"])
def generate_gcode_route():
    try:
        data = request.get_json(force=True, silent=True) or {}
        model_path = data.get("model_path")
        if not model_path or not model_path.startswith("/models/"):
            return jsonify({"success": False, "error": "Некорректный model_path"})
        stl_abs = MODELS / Path(model_path).name
        if not stl_abs.exists():
            return jsonify({"success": False, "error": "STL не найден"})

        controller = data.get("controller", "fanuc")
        operation_type = data.get("operation_type", "milling")

        allowance_x = validate_float(data.get("allowance_x", 0.0), 0.0, -10.0, 10.0)
        allowance_y = validate_float(data.get("allowance_y", 0.0), 0.0, -10.0, 10.0)
        allowance_z = validate_float(data.get("allowance_z", 0.0), 0.0, -10.0, 10.0)

        params = {
            "tool_diam": validate_float(data.get("tool", 3.0), 3.0, 0.1, 50.0),
            "stepover": validate_float(data.get("stepover", 0.4), 0.4, 0.05, 0.95),
            "feed": validate_float(data.get("feed", 300.0), 300.0, 10.0, 5000.0),
            "plunge": validate_float(data.get("plunge", 120.0), 120.0, 10.0, 2000.0),
            "clearance": validate_float(data.get("clearance", 5.0), 5.0, 1.0, 50.0),
            "spindle": validate_int(data.get("spindle", 8000), 8000, 1000, 24000) if data.get("spindle") else None,
            "dir_axis": str(data.get("dir", "X")).upper(),
            "origin": str(data.get("origin", "bbox_min")),
            "stepdown": validate_float(data.get("stepdown", 0.0), 0.0, 0.0, 50.0),
            "waterline": bool(data.get("waterline", False)),
            "waterline_dz": validate_float(data.get("waterline_dz", 0.0), 0.0, 0.0, 50.0),
            "finish_stepover": validate_float(data.get("finish_stepover", 0.0), 0.4, 0.05, 0.95) or None,
            "allowance_x": allowance_x,
            "allowance_y": allowance_y,
            "allowance_z": allowance_z,
            "controller": controller,
            "operation_type": operation_type
        }

        gname = f"gcode_{controller}_{operation_type}_{Path(stl_abs).stem}.nc"
        gout = TEMP / gname

        meta = generate_raster_gcode(stl_abs, gout, **params)

        return jsonify({
            "success": True,
            "gcode_path": f"/download_gcode?name={gname}",
            "grid": meta.get("grid", {}),
            "origin": meta.get("origin", {}),
            "controller": controller,
            "operation": operation_type
        })
    except Exception as e:
        logger.error("G-code generation failed: %s", e, exc_info=True)
        return jsonify({"success": False, "error": str(e)})