# ---- CAM geometry preparation ----
def prepare_bins(tris, step_xy: float, xmin: float, xmax: float, ymin: float, ymax: float):
    nx = max(16, min(96, int((xmax - xmin) / max(1e-6, step_xy * 2))))
    ny = max(16, min(96, int((ymax - ymin) / max(1e-6, step_xy * 2))))
    sx = (xmax - xmin) / nx if nx > 0 else 1.0
    sy = (ymax - ymin) / ny if ny > 0 else 1.0
    bins = [[[] for _ in range(ny)] for _ in range(nx)]
    coeffs_list = []

    def tri_coeff(tri):
        (x1, y1, z1), (x2, y2, z2), (x3, y3, z3) = tri
        ux, uy, uz = x2 - x1, y2 - y1, z2 - z1
        vx, vy, vz = x3 - x1, y3 - y1, z3 - z1
        A = uy * vz - uz * vy
        B = uz * vx - ux * vz
        C = ux * vy - uy * vx
        if abs(C) < 1e-12:
            return None
        D = -(A * x1 + B * y1 + C * z1)
        minx, maxx = min(x1, x2, x3), max(x1, x2, x3)
        miny, maxy = min(y1, y2, y3), max(y1, y2, y3)
        return (A, B, C, D, minx, maxx, miny, maxy, (x1, y1, z1), (x2, y2, z2), (x3, y3, z3))

    for tri in tris:
        c = tri_coeff(tri)
        if c is None:
            continue
        idx = len(coeffs_list)
        coeffs_list.append(c)
        minx, maxx, miny, maxy = c[4:8]
        i0 = int(max(0, min(nx - 1, math.floor((minx - xmin) / sx))))
        i1 = int(max(0, min(nx - 1, math.floor((maxx - xmin) / sx))))
        j0 = int(max(0, min(ny - 1, math.floor((miny - ymin) / sy))))
        j1 = int(max(0, min(ny - 1, math.floor((maxy - ymin) / sy))))
        for i in range(i0, i1 + 1):
            for j in range(j0, j1 + 1):
                bins[i][j].append(idx)
    return bins, coeffs_list, nx, ny, sx, sy

def point_in_tri_xy(px: float, py: float, a: Tuple, b: Tuple, c: Tuple) -> bool:
    ax, ay, _ = a
    bx, by, _ = b
    cx, cy, _ = c
    v0x, v0y = cx - ax, cy - ay
    v1x, v1y = bx - ax, by - ay
    v2x, v2y = px - ax, py - ay
    d00 = v0x * v0x + v0y * v0y
    d01 = v0x * v1x + v0y * v1y
    d11 = v1x * v1x + v1y * v1y
    d20 = v2x * v0x + v2y * v0y
    d21 = v2x * v1x + v2y * v1y
    denom = d00 * d11 - d01 * d01
    if abs(denom) < 1e-12:
        return False
    v = (d11 * d20 - d01 * d21) / denom
    w = (d00 * d21 - d01 * d20) / denom
    u = 1.0 - v - w
    return u >= -1e-9 and v >= -1e-9 and w >= -1e-9

def z_for(px: float, py: float, coeffs: Tuple) -> Optional[float]:
    A, B, C, D, minx, maxx, miny, maxy, a, b, c = coeffs
    if not (minx - 1e-9 <= px <= maxx + 1e-9 and miny - 1e-9 <= py <= maxy + 1e-9):
        return None
    if not point_in_tri_xy(px, py, a, b, c):
        return None
    return -(A * px + B * py + D) / C

def build_top_sampler(stl_path: Path, step_xy: float) -> Tuple[Tuple, callable]:
    if stlmesh is None:
        raise RuntimeError("numpy-stl not installed")
    m = stlmesh.Mesh.from_file(str(stl_path))
    tris = m.vectors
    xs, ys, zs = m.x, m.y, m.z
    xmin, xmax = float(xs.min()), float(xs.max())
    ymin, ymax = float(ys.min()), float(ys.max())
    zmin, zmax = float(zs.min()), float(zs.max())
    bins, coeffs, nx, ny, sx, sy = prepare_bins(tris, step_xy, xmin, xmax, ymin, ymax)

    def z_func(px: float, py: float) -> Optional[float]:
        i = int(min(nx - 1, max(0, math.floor((px - xmin) / sx))))
        j = int(min(ny - 1, max(0, math.floor((py - ymin) / sy))))
        best = None
        for di in (-1, 0, 1):
            ii = i + di
            if not (0 <= ii < nx):
                continue
            for dj in (-1, 0, 1):
                jj = j + dj
                if not (0 <= jj < ny):
                    continue
                for idx in bins[ii][jj]:
                    z = z_for(px, py, coeffs[idx])
                    if z is not None and (best is None or z > best):
                        best = z
        return best

    return (xmin, xmax, ymin, ymax, zmin, zmax), z_func

# ---- Controller and operation-specific G-code functions ----
def get_controller_settings(controller: str) -> Dict:
    """Get controller-specific G-code settings"""
    settings = {
        "fanuc": {
            "header": ["G90", "G17", "G21", "G54"],
            "spindle_on": "M3 S{spindle}",
            "spindle_off": "M5",
            "coolant_on": "M8",
            "coolant_off": "M9",
            "rapid": "G0",
            "linear": "G1",
            "program_end": "M30"
        },
        "siemens": {
            "header": ["G90", "G17", "G71", "G54"],
            "spindle_on": "M3 S{spindle}",
            "spindle_off": "M5",
            "coolant_on": "M7",
            "coolant_off": "M9",
            "rapid": "G0",
            "linear": "G1",
            "program_end": "M2"
        },
        "heidenhain": {
            "header": ["* - Generated by CNCera", "BLK FORM 0.1 Z X+0 Y+0 Z-50"],
            "spindle_on": "SPINDLE ON CW SPEED {spindle}",
            "spindle_off": "SPINDLE OFF",
            "coolant_on": "COOLANT ON",
            "coolant_off": "COOLANT OFF",
            "rapid": "L",
            "linear": "L",
            "program_end": "END PGM"
        },
        "gsk": {
            "header": ["G90", "G17", "G21", "G54"],
            "spindle_on": "M3 S{spindle}",
            "spindle_off": "M5",
            "coolant_on": "M8",
            "coolant_off": "M9",
            "rapid": "G00",
            "linear": "G01",
            "program_end": "M30"
        },
        "mazak": {
            "header": ["G90", "G17", "G21", "G54"],
            "spindle_on": "M3 S{spindle}",
            "spindle_off": "M5",
            "coolant_on": "M8",
            "coolant_off": "M9",
            "rapid": "G0",
            "linear": "G1",
            "program_end": "M99"
        }
    }
    return settings.get(controller, settings["fanuc"])

# ---- Marching Squares for waterline ----
def marching_squares(Z: List[List[float]], xs: List[float], ys: List[float], level: float) -> List[List[Tuple]]:
    ny, nx = len(Z), len(Z[0]) if Z else 0
    if nx < 2 or ny < 2:
        return []
    segs = []
    for j in range(ny - 1):
        for i in range(nx - 1):
            z00, z10 = Z[j][i], Z[j][i + 1]
            z01, z11 = Z[j + 1][i], Z[j + 1][i + 1]
            c = 0
            if z00 > level:
                c |= 1
            if z10 > level:
                c |= 2
            if z11 > level:
                c |= 4
            if z01 > level:
                c |= 8
            if c == 0 or c == 15:
                continue
            x0, x1 = xs[i], xs[i + 1]
            y0, y1 = ys[j], ys[j + 1]

            def interp(a: float, b: float, za: float, zb: float) -> float:
                t = 0.5 if (zb - za) == 0 else (level - za) / ((zb - za) or 1e-9)
                return a + t * (b - a)

            pts = []
            if (c & 1) != (c & 8):
                pts.append((x0, interp(y0, y1, z00, z01)))
            if (c & 2) != (c & 4):
                pts.append((x1, interp(y0, y1, z10, z11)))
            if (c & 1) != (c & 2):
                pts.append((interp(x0, x1, z00, z10), y0))
            if (c & 8) != (c & 4):
                pts.append((interp(x0, x1, z01, z11), y1))
            if len(pts) == 2:
                segs.append((pts[0], pts[1]))
            elif len(pts) == 4:
                segs.append((pts[0], pts[1]))
                segs.append((pts[2], pts[3]))

    loops = []
    used = [False] * len(segs)
    for sidx, (a, b) in enumerate(segs):
        if used[sidx]:
            continue
        used[sidx] = True
        loop = [a, b]
        changed = True
        while changed:
            changed = False
            for k, (p, q) in enumerate(segs):
                if used[k]:
                    continue
                if abs(loop[-1][0] - p[0]) < 1e-6 and abs(loop[-1][1] - p[1]) < 1e-6:
                    loop.append(q)
                    used[k] = True
                    changed = True
                elif abs(loop[-1][0] - q[0]) < 1e-6 and abs(loop[-1][1] - q[1]) < 1e-6:
                    loop.append(p)
                    used[k] = True
                    changed = True
        if len(loop) >= 3:
            loops.append(loop)
    return loops